/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.30.0-g74e2d5f (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.30.0-g74e2d5f"
#endif
#define SDL_REVISION_NUMBER 0
